[package]
name = "contained"
version = "1.4.0"
edition = "2021"
description = "Run a program in a Podman container for sandboxing"
license = "Apache-2.0"

[dependencies]
anyhow = "~1.0.100"

# bin dependencies
clap = { version = "~4.5.50", features = ["derive"] }
